import os

ROOT_DIR = os.path.dirname(__file__)

PAGE = "https://finance.yahoo.com/screener/new"

SELECTORS = {
    "region_item": "li.filterItem",
    "region_add": "li.filterAdd",
    "region_search": '//input[@placeholder="Find filters"]',
    "stocks_button": '//button[@data-test="find-stock"]',
    "table": "scr-res-table",
}

REGIONS = [
    "Argentina",
    "Austria",
    "Australia",
    "Belgium",
    "Brazil",
    "Canada",
    "Switzerland",
    "Chile",
    "China",
    "Czechia",
    "Germany",
    "Denmark",
    "Estonia",
    "Egypt",
    "Spain",
    "Finland",
    "France",
    "United Kingdom",
    "Greece",
    "Hong Kong SAR",
    "China",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "India",
    "Iceland",
    "Italy",
    "Japan",
    "South Korea",
    "Kuwait",
    "Sri Lanka",
    "Lithuania",
    "Latvia",
    "Mexico",
    "Malaysia",
    "Netherlands",
    "Norway",
    "New Zealand",
    "Peru",
    "Philippines",
    "Pakistan",
    "Poland",
    "Portugal",
    "Qatar",
    "Russia",
    "Saudi Arabia",
    "Sweden",
    "Singapore",
    "Suriname",
    "Thailand",
    "Turkey",
    "Taiwan",
    "United States",
    "Venezuela",
    "Vietnam",
    "South Africa",
]
